/**
 * guardian Controller (Basic)
 * Auto-generated by bffgen
 * 
 * Basic pass-through controller that proxies requests to backend service
 */

const guardianService = require('../services/guardian.service');

class GuardianController {
  constructor() {
    this.service = new guardianService();
  }


  /**
   * GET /api/news/guardian/headlines
   * @public
   */
  async getApiNewsGuardianHeadlines(req, res, next) {
    try {
      const result = await this.service.getApiNewsGuardianHeadlines(req.params, req.query, req.body, req.headers);
      res.json(result);
    } catch (error) {
      next(error);
    }
  }

  /**
   * GET /api/news/guardian/search
   * @public
   */
  async getApiNewsGuardianSearch(req, res, next) {
    try {
      const result = await this.service.getApiNewsGuardianSearch(req.params, req.query, req.body, req.headers);
      res.json(result);
    } catch (error) {
      next(error);
    }
  }

}

module.exports = new GuardianController();

