/**
 * nytimes Controller (Basic)
 * Auto-generated by bffgen
 * 
 * Basic pass-through controller that proxies requests to backend service
 */

const nytimesService = require('../services/nytimes.service');

class NytimesController {
  constructor() {
    this.service = new nytimesService();
  }


  /**
   * GET /api/news/nytimes/headlines
   * @public
   */
  async getApiNewsNytimesHeadlines(req, res, next) {
    try {
      const result = await this.service.getApiNewsNytimesHeadlines(req.params, req.query, req.body, req.headers);
      res.json(result);
    } catch (error) {
      next(error);
    }
  }

  /**
   * GET /api/news/nytimes/search
   * @public
   */
  async getApiNewsNytimesSearch(req, res, next) {
    try {
      const result = await this.service.getApiNewsNytimesSearch(req.params, req.query, req.body, req.headers);
      res.json(result);
    } catch (error) {
      next(error);
    }
  }

}

module.exports = new NytimesController();

