/**
 * Request ID Middleware
 * Auto-generated by bffgen
 * 
 * Generates unique ID for each request to track across logs
 */

const crypto = require('crypto');
const logger = require('../utils/logger');

/**
 * Generate unique request ID
 */
function generateRequestId() {
  return crypto.randomBytes(16).toString('hex');
}

/**
 * Request ID middleware
 * Adds unique ID to each request for correlation
 */
function requestId(req, res, next) {
  // Check if request ID already exists (from load balancer or proxy)
  const existingId = req.headers['x-request-id'] || 
                     req.headers['x-correlation-id'] ||
                     req.headers['x-trace-id'];
  
  // Use existing ID or generate new one
  req.id = existingId || generateRequestId();
  
  // Add request ID to response headers
  res.setHeader('X-Request-ID', req.id);
  
  // Add request ID to logger context
  req.log = logger.child({ requestId: req.id });
  
  next();
}

module.exports = requestId;

