linters:
  enable:
    - errcheck
    - bodyclose
    - govet
    - misspell
  disable-all: false

linters-settings:
  errcheck:
    exclude-functions:
      - (viper.BindPFlag)
      - (os.Chdir)
      - (os.WriteFile)
      - (os.Setenv)
      - (os.MkdirAll)
      - (json.Unmarshal)

run:
  timeout: 5m
  skip-dirs:
    - vendor
    - node_modules
    - dist
    - test-project
    - templates
    - examples

issues:
  max-same-issues: 0
  exclude-rules:
    - path: "_test\\.go"
      linters:
        - errcheck
        - gosec
    - text: "Error return value of `(viper\\.BindPFlag|pt\\.bar\\.(Add|Set|Finish))` is not checked"
      linters:
        - errcheck
