"""
FastAPI BFF Main Application
Auto-generated by bffgen
"""
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import List, Optional
import httpx
import os
from dotenv import load_dotenv

load_dotenv()

app = FastAPI(
    title="{{PROJECT_NAME}} BFF",
    description="Backend-for-Frontend service aggregating multiple microservices",
    version="1.0.0"
)

# CORS configuration
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Configure appropriately for production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Configuration
PORT = int(os.getenv("PORT", "{{PORT}}"))
BACKEND_API_URL = os.getenv("BACKEND_API_URL", "http://localhost:3000")

# Pydantic Models
class User(BaseModel):
    id: int
    name: str
    email: str

class Post(BaseModel):
    id: int
    userId: int
    title: str
    body: str

class UserWithPosts(BaseModel):
    user: User
    posts: List[Post]

# HTTP Client
async def get_http_client():
    async with httpx.AsyncClient(timeout=10.0) as client:
        yield client

# Health Check
@app.get("/healthz")
async def health_check():
    """Health check endpoint for Kubernetes probes"""
    return {"status": "ok"}

# Aggregation Endpoints
@app.get("/api/users/{user_id}", response_model=User)
async def get_user(user_id: int):
    """Fetch user from backend service"""
    async with httpx.AsyncClient() as client:
        try:
            response = await client.get(f"{BACKEND_API_URL}/users/{user_id}")
            response.raise_for_status()
            return response.json()
        except httpx.HTTPStatusError as e:
            raise HTTPException(status_code=e.response.status_code, detail=str(e))
        except Exception as e:
            raise HTTPException(status_code=500, detail=f"Backend error: {str(e)}")

@app.get("/api/users/{user_id}/posts", response_model=List[Post])
async def get_user_posts(user_id: int):
    """Fetch posts for a specific user"""
    async with httpx.AsyncClient() as client:
        try:
            response = await client.get(f"{BACKEND_API_URL}/posts?userId={user_id}")
            response.raise_for_status()
            return response.json()
        except httpx.HTTPStatusError as e:
            raise HTTPException(status_code=e.response.status_code, detail=str(e))
        except Exception as e:
            raise HTTPException(status_code=500, detail=f"Backend error: {str(e)}")

@app.get("/api/users/{user_id}/aggregate", response_model=UserWithPosts)
async def get_user_aggregate(user_id: int):
    """Aggregate user and their posts in a single request"""
    async with httpx.AsyncClient() as client:
        try:
            # Parallel requests for better performance
            user_task = client.get(f"{BACKEND_API_URL}/users/{user_id}")
            posts_task = client.get(f"{BACKEND_API_URL}/posts?userId={user_id}")
            
            user_response, posts_response = await asyncio.gather(user_task, posts_task)
            
            user_response.raise_for_status()
            posts_response.raise_for_status()
            
            return {
                "user": user_response.json(),
                "posts": posts_response.json()
            }
        except httpx.HTTPStatusError as e:
            raise HTTPException(status_code=e.response.status_code, detail=str(e))
        except Exception as e:
            raise HTTPException(status_code=500, detail=f"Aggregation error: {str(e)}")

if __name__ == "__main__":
    import uvicorn
    import asyncio
    
    uvicorn.run(app, host="0.0.0.0", port=PORT)
