#!/usr/bin/env node

/**
 * Cache Clear Script
 * Auto-generated by bffgen
 * 
 * Clears Redis cache or provides instructions
 * Usage: npm run cache:clear
 */

require('dotenv').config();

async function clearCache() {
  const redisUrl = process.env.REDIS_URL;

  if (!redisUrl) {
    console.log('ℹ️  REDIS_URL not configured');
    console.log('Cache is running in-memory only (cleared on restart)');
    console.log('\nTo use Redis:');
    console.log('1. Install Redis: docker-compose up redis');
    console.log('2. Set REDIS_URL in .env: REDIS_URL=redis://localhost:6379');
    return;
  }

  try {
    const redis = require('redis');
    const client = redis.createClient({ url: redisUrl });
    
    await client.connect();
    console.log('🔗 Connected to Redis');

    // Clear all keys with bff: prefix
    const keys = await client.keys('bff:*');
    
    if (keys.length === 0) {
      console.log('✅ Cache is already empty');
    } else {
      await client.del(keys);
      console.log(`✅ Cleared ${keys.length} cache entries`);
    }

    await client.quit();
  } catch (error) {
    console.error('❌ Failed to clear cache:', error.message);
    process.exit(1);
  }
}

// Run if executed directly
if (require.main === module) {
  clearCache()
    .then(() => {
      console.log('✨ Cache cleared successfully');
      process.exit(0);
    })
    .catch(error => {
      console.error('Error:', error);
      process.exit(1);
    });
}

module.exports = clearCache;

