/**
 * Swagger Setup for Express
 * Auto-generated by bffgen
 */

const swaggerUi = require('swagger-ui-express');
const swaggerJsdoc = require('swagger-jsdoc');
const swaggerConfig = require('./swagger-config');

/**
 * Swagger JSDoc options
 */
const swaggerJsdocOptions = {
  definition: swaggerConfig,
  apis: [
    './src/routes/*.js',
    './src/controllers/*.js',
    './src/index.js'
  ]
};

/**
 * Generate Swagger specification
 */
const swaggerSpec = swaggerJsdoc(swaggerJsdocOptions);

/**
 * Setup Swagger UI middleware
 * @param {Express} app - Express application instance
 */
function setupSwagger(app) {
  // Swagger UI options
  const swaggerUiOptions = {
    explorer: true,
    customCss: '.swagger-ui .topbar { display: none }',
    customSiteTitle: 'news-aggregator API Documentation'
  };

  // Serve Swagger UI
  app.use('/api-docs', swaggerUi.serve);
  app.get('/api-docs', swaggerUi.setup(swaggerSpec, swaggerUiOptions));

  // Serve raw OpenAPI spec as JSON
  app.get('/api-docs.json', (req, res) => {
    res.setHeader('Content-Type', 'application/json');
    res.send(swaggerSpec);
  });

  console.log('📚 Swagger UI available at: http://localhost:' + (process.env.PORT || '8080') + '/api-docs');
  console.log('📄 OpenAPI spec available at: http://localhost:' + (process.env.PORT || '8080') + '/api-docs.json');
}

module.exports = {
  setupSwagger,
  swaggerSpec
};

